name: Blank Workflow (No Node)

on: [push]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify
        run: echo "No Node project detected. Add package.json to use Oxygen deploy."
